config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import os

def trigger_error(request):
    division_by_zero = 1 / 0

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path(os.environ.get("ADMIN_URL", "admin/"), admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as rooms_view

app_name = "core"

urlpatterns = [path("", rooms_view.HomeView.as_view(), name="home")]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"


urlpatterns = [
    path("toggle/<int:room_pk>/", views.toggle_room, name="toggle-room"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
]

rooms/urls.py
from django.urls import path
from . import views as room_views

app_name = "rooms"

urlpatterns = [
    path("create/", room_views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", room_views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", room_views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", room_views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", room_views.AddPhotoView.as_view(), name="add-photos"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        room_views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        room_views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", room_views.RoomSearch.as_view(), name="search"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/", views.complete_verification, name="complete-verification"
    ),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path(
        "update-password/", views.UpdatePasswordView.as_view(), name="update-password"
    ),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
    path("switch-language/", views.switch_language, name="switch-language"),
]

templates/partials/footer.html
{% load i18n %}
<footer class="container mx-auto text-center py-10 border-t font-medium text-gray-400">
    <div class="flex flex-col">
        <span>
            {% trans "Please Don`t Copy" %}
        </span>
        &copy; @ 2019 Airbnb , Inc. {% trans "All rights reserved" %}.
    </div>
    <div class="flex mt-10 ">
        {% get_current_language as LANGUAGE_CODE %}
        <select id="js-lang" class="w-1/5 h-15 text-sm px-1 py-1">
            <option value="en" {% if LANGUAGE_CODE == 'en' %} selected {% endif %}>English</option>
            <option value="ko" {% if LANGUAGE_CODE == 'ko' %} selected {% endif %}>Korea</option>
        </select>
    </div>
</footer>

templates/partials/messages.html
{% if messages %}
<ul class="absolute top-0 mx-auto  flex justify-center right-0 left-0 py-0">
    {% for message in messages %}
    <li class="message font-medium px-6 py-4 z-10 w-64 text-center rounded-full bg-gray-600 text-white {% if message.tags %} {{ message.tags }} {% endif %}">{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

templates/partials/nav.html
<ul class="flex items-center text-sm font-medium h-full">
  {% if user.is_authenticated %}
    <li class="nav_link">
      <a href="{% url 'users:switch-hosting' %}">
        {% if request.session.is_hosting %}
            Start Hosting
        {% else %}
          Stop Hosting
        {% endif %}
      </a>
    </li>
    {% if request.session.is_hosting %}
    <li class="nav_link">
      <a href="{% url 'rooms:create' %}">Create Room</a>
    </li>
    {% endif %}
    <li class="nav_link">
      <a href="{{user.get_absolute_url}}">Profile</a>
    </li>
    <li class="nav_link">
      <a href="{% url 'lists:see-favs' %}">Favorites({{user.list.rooms.count}})</a>
    </li>
    <li class="nav_link"><a href="{% url 'users:logout' %}">Logout</a></li>
  {% else %}
    <li class="nav_link"><a href="{% url 'users:login' %}">Login</a></li>
    <li class="nav_link"><a href="{% url 'users:signup' %}">SignUp</a></li>
  {% endif %} 
</ul>

templates/partials/social_login.html
<div class="flex flex-col w-full">
    <a href="{% url 'users:github-login' %}" class="btn border-2 text-gray-700 border-gray-600 ">
        <i class="fab fa-github-alt mr-2 fa-lg"></i>
        Continue with Github
    </a>

    <a href="{% url 'users:kakao-login' %}" class="btn border-2 text-yellow-800 border-yellow-400 bg-yellow-400">
        <i class="fas fa-comment mr-2 fa-lg"></i>
        Continue with kakao
    </a>
</div>

<div class="flex items-center w-full my-5">
    <div class="h-px w-full bg-gray-500"></div>
    <span class="text-gray-500 text-sm mx-4 font-bold font-medium">or</span>
    <div class="h-px w-full bg-gray-500"></div>
</div>