config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import os

def trigger_error(request):
    division_by_zero = 1 / 0

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path(os.environ.get("ADMIN_URL", "admin/"), admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as rooms_view

app_name = "core"

urlpatterns = [path("", rooms_view.HomeView.as_view(), name="home")]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"


urlpatterns = [
    path("toggle/<int:room_pk>/", views.toggle_room, name="toggle-room"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
]

rooms/urls.py
from django.urls import path
from . import views as room_views

app_name = "rooms"

urlpatterns = [
    path("create/", room_views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", room_views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", room_views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", room_views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", room_views.AddPhotoView.as_view(), name="add-photos"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        room_views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        room_views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", room_views.RoomSearch.as_view(), name="search"),
]

rooms/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django_countries.fields import CountryField

from core import models as core_models
from cal import Calendar


class AbstractItem(core_models.TimeStampedModel):

    """ Abstract Item"""

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class RoomType(AbstractItem):
    """ RoomType Object Definition """

    class Meta:
        verbose_name = "Room Type"


class Amenity(AbstractItem):

    """ Amenity Object Definition """

    class Meta:
        verbose_name_plural = "Amenities"


class Facility(AbstractItem):

    """ Facility Object Definition """

    class Meta:
        verbose_name_plural = "Facilities"


class HouseRule(AbstractItem):

    """ House Model Definition """

    class Meta:
        verbose_name = "House Rule"


class Photo(core_models.TimeStampedModel):
    """ Photo Model Definition """

    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to="room_photos")
    room = models.ForeignKey("Room", related_name="photos", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption


class Room(core_models.TimeStampedModel):

    """ Room Model Definition """

    name = models.CharField(max_length=140)
    description = models.TextField()
    country = CountryField()
    city = models.CharField(max_length=80)
    price = models.IntegerField()
    address = models.CharField(max_length=140)
    guests = models.IntegerField()
    beds = models.IntegerField()
    bedrooms = models.IntegerField()
    baths = models.IntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField(default=False)
    host = models.ForeignKey(
        "users.User", related_name="rooms", on_delete=models.CASCADE
    )
    room_type = models.ForeignKey(
        "RoomType", related_name="rooms", on_delete=models.SET_NULL, null=True
    )
    amenities = models.ManyToManyField("Amenity", related_name="rooms", blank=True)
    facilities = models.ManyToManyField("Facility", related_name="rooms", blank=True)
    house_rules = models.ManyToManyField("HouseRule", related_name="rooms", blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.city = str.capitalize(self.city)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("rooms:detail", kwargs={"pk": self.pk})

    def total_rating(self):
        all_reviews = self.reviews.all()
        all_ratings = 0
        for review in all_reviews:
            all_ratings += review.rating_average()
        result = 0
        if len(all_reviews):
            result = all_ratings / len(all_reviews)
        return result

    def first_photo(self):
        try:
            (photo,) = self.photos.all()[:1]
            return photo.file.url
        except ValueError:
            return None

    def get_next_four_photo(self):
        photos = self.photos.all()[1:5]
        return photos

    def get_calendars(self):
        now = timezone.now()
        this_year = now.year
        this_month = now.month
        if this_month == 12:
            next_year = this_year + 1
            next_month = 1
        else:
            next_year = this_year
            next_month = this_month + 1
        this_month_calendar = Calendar(this_year, this_month)
        next_next_calendar = Calendar(next_year, next_month)
        return (this_month_calendar, next_next_calendar)

rooms/forms.py
from django import forms
from django_countries.fields import CountryField
from . import models


class SearchForm(forms.Form):
    city = forms.CharField()
    room_type = forms.ModelChoiceField(
        required=False, empty_label="any kind", queryset=models.RoomType.objects.all()
    )
    country = CountryField(default="KR").formfield()
    price = forms.IntegerField(required=False)
    guests = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    bedrooms = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)
    instant_book = forms.BooleanField(required=False)
    superhost = forms.BooleanField(required=False)
    amenities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Amenity.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    facilities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Facility.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )


class CreatePhotoForm(forms.ModelForm):
    class Meta:
        model = models.Photo
        fields = ("caption", "file")

    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)
        room = models.Room.objects.get(pk=pk)
        photo.room = room
        photo.save()


class CreateRoomForm(forms.ModelForm):
    class Meta:
        model = models.Room
        fields = (
            "name",
            "description",
            "country",
            "city",
            "price",
            "address",
            "guests",
            "beds",
            "bedrooms",
            "baths",
            "check_in",
            "check_out",
            "instant_book",
            "room_type",
            "amenities",
            "facilities",
            "house_rules",
        )

    def save(self, *args, **kwargs):
        room = super().save(commit=False)
        return room

rooms/views.py
from django.views.generic import ListView, DetailView, View, UpdateView, FormView
from django.contrib.messages.views import SuccessMessageMixin
from django.http import Http404
from django.utils import timezone
from django.shortcuts import render, reverse, redirect
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from . import models
from . import forms
from users import mixins as user_mixins


class HomeView(ListView):

    """ HomeView Definition """

    model = models.Room
    paginate_by = 12
    ordering = "created"
    paginate_orphans = 5
    context_object_name = "rooms"  # default object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        now = timezone.now()
        context["now"] = now
        return context


class RoomDetail(DetailView):

    """ RoomDetail Definition """

    model = models.Room
    # auto
    # context : { "room" : room }


class EditRoomView(user_mixins.LoginInOnlyView, UpdateView):
    model = models.Room
    template_name = "rooms/room_edit.html"
    fields = (
        "name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "guests",
        "beds",
        "bedrooms",
        "baths",
        "check_in",
        "check_out",
        "instant_book",
        "room_type",
        "amenities",
        "facilities",
        "house_rules",
    )

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404()
        return room


class RoomPhotosView(user_mixins.LoginInOnlyView, DetailView):
    model = models.Room
    template_name = "rooms/room_photos.html"

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404()
        return room


class RoomSearch(View):
    def get(self, request):
        form = forms.SearchForm(request.GET)
        if form.is_valid():
            city = form.cleaned_data.get("city")
            room_type = form.cleaned_data.get("room_type")
            country = form.cleaned_data.get("country")
            price = form.cleaned_data.get("price")
            guests = form.cleaned_data.get("guests")
            beds = form.cleaned_data.get("beds")
            bedrooms = form.cleaned_data.get("bedrooms")
            baths = form.cleaned_data.get("baths")
            instant_book = form.cleaned_data.get("instant_book")
            superhost = form.cleaned_data.get("superhost")
            amenities = form.cleaned_data.get("amenities")
            facilities = form.cleaned_data.get("facilities")

            filter_kwargs = {}

            filter_kwargs["city__startswith"] = city
            filter_kwargs["country"] = country
            if room_type is not None:
                filter_kwargs["room_type"] = room_type

            if price is not None:
                filter_kwargs["price__lte"] = price

            if guests is not None:
                filter_kwargs["guests__lte"] = guests

            if beds is not None:
                filter_kwargs["beds__lte"] = beds

            if bedrooms is not None:
                filter_kwargs["bedrooms__lte"] = bedrooms

            if baths is not None:
                filter_kwargs["baths__lte"] = baths

            if instant_book is not None:
                filter_kwargs["instant_book"] = instant_book

            if superhost is not None:
                filter_kwargs["host__superhost"] = superhost

            for amenity in amenities:
                filter_kwargs["amenities"] = amenity
            for facility in facilities:
                filter_kwargs["facilities"] = facility

            qs = models.Room.objects.filter(**filter_kwargs)

            paginator = Paginator(qs, 5, orphans=5)

            page = request.GET.get("page", 1)
            rooms = paginator.get_page(page)

            return render(request, "rooms/search.html", {"form": form, "rooms": rooms})
        else:
            form = forms.SearchForm()

        return render(request, "rooms/search.html", {"form": form})


@login_required
def delete_photo(request, room_pk, photo_pk):
    user = request.user
    try:
        room = models.Room.objects.get(pk=room_pk)
        if room.host.pk != user.pk:
            messages.error(request, "Can`t delete that photo")
        else:
            models.Photo.objects.filter(pk=photo_pk).delete()
            messages.success(request, "Photo Deleted")
    except models.Room.DoesNotExist:
        return redirect(reverse("core:home"))

    return redirect(reverse("rooms:photos", kwargs={"pk": room_pk}))


class EditPhotoView(user_mixins.LoginInOnlyView, SuccessMessageMixin, UpdateView):
    model = models.Photo
    template_name = "rooms/edit_photo.html"
    pk_url_kwarg = "photo_pk"
    fields = ("caption",)
    success_message = "Photo Updated"

    def get_success_url(self):
        room_pk = self.kwargs.get("room_pk")
        return reverse("rooms:photos", kwargs={"pk": room_pk})


class AddPhotoView(user_mixins.LoginInOnlyView, FormView):
    model = models.Photo
    template_name = "rooms/photo_create.html"
    form_class = forms.CreatePhotoForm

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        form.save(pk)
        messages.success(self.request, "Photo Upload.")
        return redirect(reverse("rooms:photos", kwargs={"pk": pk}))


class CreateRoomView(user_mixins.LoginInOnlyView, FormView):
    form_class = forms.CreateRoomForm
    template_name = "rooms/room_create.html"

    def form_valid(self, form):
        room = form.save()
        room.host = self.request.user
        room.save()
        form.save_m2m()
        messages.success(self.request, "Create Room")
        return redirect(reverse("rooms:detail", kwargs={"pk": room.pk}))

templates/rooms/detail.html
{% extends "base.html" %}

{% block page_name %}
    Detail
{% endblock page_name %}

{% block content %}
<div>

    <h1>
        {{room.name}}
    </h1>
    <h3>
        {{room.description}}
    </h3>
</div>
<div>
    <h2> By: {{room.host.username}} 
    {% if room.host.superhost %}
        (superhost)
    {% endif %}
    <h2>

    <h3>amenity</h3>
    <ul>
    {% for a in room.amenities.all  %}
        <li>{{a}}</li>  
    {% endfor %}
    </ul>

    <h3>Facility</h3>
    <ul>
    {% for f in room.facilities.all  %}
        <li>{{f}}</li>  
    {% endfor %}
    </ul>
</div>
{% endblock content %}

templates/rooms/edit_photo.html
{% extends "base.html" %}
{% block page_title %}
    Update Photo
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
<div
    class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto mt-40 mb-10 flex flex-col items-center border p-6 border-gray-400">

    {% include "mixins/room/room_form.html" with form=form cta="Update Photo" %}
    
</div>

{% endblock content %}

templates/rooms/photo_create.html
{% extends "base.html" %}
{% block page_title %}
Upload Photo
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
<div
    class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto mt-40 mb-10 flex flex-col items-center border p-6 border-gray-400">

    {% include "mixins/room/room_form.html" with form=form cta="Upload Photo" %}

</div>

{% endblock content %}

templates/rooms/room_create.html
{% extends "base.html" %}
{% block page_title %}
Create Room
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
<div
    class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto mt-40 mb-10 flex flex-col items-center border p-6 border-gray-400">

    {% include "mixins/room/room_form.html" with form=form cta="Create Room" %}
</div>

{% endblock content %}

templates/rooms/room_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load is_booked %}
{% load on_favs %}
{% block page_title %}
    {{room.name}}
{% endblock page_title %}

{% block content %}
    <div class="container -mt-5 max-w-full h-75vh flex mb-20">
        <div class="h-full w-1/2 bg-cover bg-center" style="background-image: url({{room.first_photo}});"></div>
        
        <div class="h-full w-1/2 flex flex-wrap">
            {% for photo in room.get_next_four_photo %}
            <div style="background-image: url({{photo.file.url}});" class="w-1/2 h-auto bg-cover bg-center border border-gray-500 border-1"></div>
            {% endfor%}
        </div>
    </div>
    <div class="container mx-auto flex justify-around pb-56">
        <div class="w-1/2">
            <div class="flex justify-between">
                <div class="mb-5">
                    <div class="text-3xl font-medium mb-px">{{room.name}}</div>
                    <span class="text-gray-600 font-light">{{room.city}}</span>
                </div>
                <a href="{{room.host.get_absolute_url}}" class="flex flex-col items-center">
                    {% include "mixins/profile_avatar.html" with user=room.host%}
                    <span class="mt-3 font-light text-gray-500">{{room.host.first_name}}</span>
                </a>
            </div>
            {% on_favs room as on_favs_boolean %}
            {% if on_favs_boolean %}
                <a class=" block mb-10 w-1/3 font-bold text-teal-300" href="{% url "lists:toggle-room" room.pk %}?action=remove">{% trans 'Remove From Favorite' %}</a>
            {% else %}
                <a class=" block mb-10 w-1/3 font-bold text-teal-300" href="{% url "lists:toggle-room" room.pk %}?action=add">{% trans 'Save to Favorite' %}</a>
            {% endif %}
            <div class="flex border-section">
                <span class="mr-5 font-light">{{room.room_type}}</span>
                <span class="mr-5 font-light">{{room.beds}} bed{{room.beds | pluralize}}</span>
                <span class="mr-5 font-light">{{room.bedrooms}} bedroom{{room.bedrooms | pluralize}}</span>
                <span class="mr-5 font-light">{{room.baths}} bath{{room.baths | pluralize}}</span>
                <span class="mr-5 font-light">{{room.guests}} guest{{room.guests | pluralize}}</span>
            </div>
            <p class="border-section">

                {{room.description}}
            </p>
            <div class="border-section ">
                <h4 class="font-medium text-lg mb-5">Amenities</h4>
                {% for a in room.amenities.all %}
                    <li class="mb-2">{{a}}</li>
                {% endfor %}
            </div>
            <div class="border-section ">
                <h4 class="font-medium text-lg mb-5">Facilities</h4>
                {% for f in room.facilities.all %}
                <li class="mb-2">{{f}}</li>
                {% endfor %}
            </div>
            <div class="border-section ">
                <h4 class="font-medium text-lg mb-5">House Rule</h4>
                <ul>
                    {% for h in room.house_rules.all %}
                    <li class="mb-2">{{h}}</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="mt-5">
                <h4 class="font-medium text-2xl mb-5">Reviews</h4>
                <div class="flex items-center">
                    <div>
                        <i class="fas fa-star text-teal-400"></i>
                        <span class="font-bold">{{room.total_rating|floatformat:2}}</span>
                    </div>
                    <div class="h-5 w-px bg-gray-400 mx-5"></div>
                    <div>
                        <span class="font-bold text-xl">{{room.reviews.count}}</span>
                        <span>review{{room.reviews.count|pluralize}}</span>
                    </div>
                </div>
                <div>
                    {% for review in room.reviews.all %}
                        <div class="border-section">
                            <div class="mb-3 flex">
                                <div>
                                    {% include "mixins/profile_avatar.html" with user=review.user h_and_w='h-10 w-10' text='text-xl' %}
                                </div>
                                <div class="flex flex-col ml-3">
                                    <span class="font-medium">{{review.user.first_name}}</span>
                                    <span class="text-gray-500">{{review.created|date:'F Y'}}</span>
                                </div>
                            </div>
                            <p>{{review.review}}</p>
                        </div>
                    {% endfor %}
                </div>

            </div>
        </div>
        <div class="w-1/3">
            {% if room.host == user %}
                <a href="{% url 'rooms:edit' pk=room.id %}" class="btn-link block">Edit Room</a>
            {% else %}
                {% if not request.session.is_hosting %}
                    {% for calendar in room.get_calendars %}
                    <div class="mb-20">
                        <span class=" font-medium text-lg mb-8 block text-center">{{calendar.get_month}} / {{calendar.year}}</span>
                        <div class="cal-grid mb-4 font-semibold">
                            {% for day in calendar.day_names %}
                            <span>{{day}}</span>
                            {% endfor %}
                        </div>
                        <div class="cal-grid">
                            {% for day in calendar.get_days %}
                                {% if day.number != 0 %}
                                    {% if day.past %}
                                        <span class="rounded bg-gray-200 w-full text-center p-1 text-gray-300">{{day}}</span>
                                    {% else %}
                                    {% is_booked room day as is_booked_bool %}
                                        {% if is_booked_bool %}
                                            <span class="rounded bg-gray-200 w-full text-center p-1 text-gray-300 line-through">{{day}}</span>
                                        {% else %}
                                            <a href="{% url "reservations:create" room.pk day.year day.month day.number %}"
                                                class="bg-gray-200 w-full text-center rounded text-gray-700 p-1 hover:bg-teal-400 hover:text-white hover:font-medium">{{day}}</a>
                                        {% endif %}
                                    {% endif %}
                                {% else %}
                                    <span></span>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                    {% endfor %}
                {% endif %}
            {% endif %}
        </div>
    </div>
{% endblock content %}

templates/rooms/room_edit.html
{% extends "base.html" %}
{% block page_title %}
{{room.name}}
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    <div
        class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto mt-40 mb-10 flex flex-col items-center border p-6 border-gray-400">

        {% include "mixins/room/room_form.html" with form=form cta="Update Room" %}
        <div class="mt-5">
            <a href="{% url 'rooms:photos' pk=room.id %}" class="font-medium text-teal-500">Edit Photos</a>
        </div>
    </div>

{% endblock content %}

templates/rooms/room_list.html
{% extends "base.html" %}
{% load i18n %}
{% block page_title %}
    Home
{% endblock page_title %}

{% block content %}
    <div class="container mx-auto">
        
        <div class="bg-gray-800 -mx-20 h-50vh mt-32 mb-20 rounded-xl bg-cover bg-center" style="background-image: url(https://images.unsplash.com/photo-1577706137622-8a0ec7f02872?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop);"></div>
    
        <div class="flex flex-wrap -mx-20">
            {% for room in rooms  %}
                {% include  'mixins/room_card.html' with room=room %}
            {% endfor %}
        </div>
        
        <div class="flex items-center justify-center mx-auto container">
            {% if page_obj.has_previous %}
                <a href="?page={{page_obj.previous_page_number}}">
                    <i class="fas fa-arrow-left fa-lg text-teal-500"></i>
                </a>
            {% endif %}
            <span class="mx-3 font-medium text-lg">
                {% blocktrans with current_page=page_obj.number total_pages=page_obj.paginator.num_pages%} Page {{ current_page }} of {{ total_pages }}{% endblocktrans %}
            </span>
            {% if page_obj.has_next %}
                <a href="?page={{page_obj.next_page_number}}">
                    <i class="fas fa-arrow-right fa-lg text-teal-500"></i>
                </a>
            {% endif %}
        </div>

    </div>
{% endblock content %}

templates/rooms/room_photos.html
{% extends "base.html" %}
{% block page_title %}
{{room.name}} Photos
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
<div class="container  mx-auto my-10 flex flex-col">
    <div class="my-10 w-full">
        <a href="{% url 'rooms:add-photos' pk=room.pk %}" class="btn-link w-1/6 block">Photo Upload</a>
    </div>
    {% for photo in room.photos.all %}
        <div class="mb-5  border p-6 border-gray-400 flex justify-between">
            <div class="flex items-start">
                <img src="{{photo.file.url}}" class="w-32 h-32"/>
                <span class="ml-5 text-xl">
                    {{photo.caption}}
                </span>
            </div>
            <div class="flex flex-col w-1/5">
                <a class="btn-link mb-5 bg-teal-500" href="{% url 'rooms:edit-photo' room_pk=room.pk photo_pk=photo.pk %}">Edit</a>
                <a class="btn-link bg-red-600" href="{% url 'rooms:delete-photo' room_pk=room.pk photo_pk=photo.pk %}">Delete</a>
            </div>
        </div>
    {% endfor %}

    <div class="flex justify-center mt-5">
        <a href="{% url 'rooms:edit' pk=room.pk %}" class="text-teal-500 font-medium font-2xl">Back to edit room</a>
    </div>
</div>
{% endblock content %}

templates/rooms/search.html
{% extends "base.html" %} 
{% block page_title %} Search {% endblock page_title%}
{% block search-bar %} 
{% endblock search-bar %} 
{% block content %}
<h2>Searching</h2>
<form name="userinput" method="get" action="{% url 'rooms:search' %}">
  {{ form.as_p }}
  <button type="summit">Search</button>
  <h3>Result</h3>
  {% for room in rooms %}
  <h4>{{ room.name }} / {{ romm.country }}</h4>
  {% endfor %}

  <p>
    <input
      id="hidden_page"
      style="display:none;"
      name="page"
      value="{{ rooms.number }}"
    />
    <span><a onClick="previous()">⬅️</a></span>
    page {{ rooms.number }} of {{ rooms.paginator.num_pages }}
    <span><a onClick="next()">➡️</a></span>
  </p>
</form>
<script>
  var page_input = document.querySelector("#hidden_page")
  max_page = {{rooms.paginator.num_pages}}
  function previous(){
      var page = Number(page_input.value)
      if (page > 1){
          page -= 1
      }
      console.log("previous" +page)
      page_input.value = String(page)
      document.userinput.submit()
  }
  function next(){
      var page = Number(page_input.value)
      if (page < max_page){
          page += 1
      }
      console.log("next" + page)
      page_input.value = String(page)
      document.userinput.submit()
  }
</script>

{% endblock content %}